-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `app`.`cad_unidade_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`cad_unidade_medida` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tx_descricao` VARCHAR(100) NULL,
  `tx_simbolo` VARCHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `app`.`cad_unidade_medida`
-- -----------------------------------------------------
START TRANSACTION;
USE `app`;
INSERT INTO `app`.`cad_unidade_medida` (`id`, `tx_descricao`, `tx_simbolo`) VALUES (NULL, 'unidade', 'un');
INSERT INTO `app`.`cad_unidade_medida` (`id`, `tx_descricao`, `tx_simbolo`) VALUES (NULL, 'dúzia', 'dz');
INSERT INTO `app`.`cad_unidade_medida` (`id`, `tx_descricao`, `tx_simbolo`) VALUES (NULL, 'mililitro', 'mL');
INSERT INTO `app`.`cad_unidade_medida` (`id`, `tx_descricao`, `tx_simbolo`) VALUES (NULL, 'litro', 'L');
INSERT INTO `app`.`cad_unidade_medida` (`id`, `tx_descricao`, `tx_simbolo`) VALUES (NULL, 'quilograma', 'Kg');
INSERT INTO `app`.`cad_unidade_medida` (`id`, `tx_descricao`, `tx_simbolo`) VALUES (NULL, 'grama', 'g');

COMMIT;